### PR TITLE
Fix/integrate latest rocksb6.20+

### PR DESCRIPTION
**Pull request by ssardana96**

### CODE REVIEW

**Review by cnlangzi — APPROVED** [review]

**Review by kushthedude — CHANGES_REQUESTED** [review]
Why are we maintaining a fork when there are no changes, or if some changes we need why arent we contributing to the upstream & increasing our tech debt?

**Comment by cnlangzi** [comment]
> Why are we maintaining a fork when there are no changes, or if some changes we need why arent we contributing to the upstream & increasing our tech debt?

some patches are added on the fork. see https://github.com/0chain/gorocksdb/pull/1/commits/9721107d4a29f0c874dc43c997fbe921ca504390

**Comment by cnlangzi** [comment]
only 6.20.3 works on Apple M1 chip. but gorocksdb is broken by rocksdb public api changes since v6.16.0 https://github.com/facebook/rocksdb/blob/e8f116deabc601a5eae011f2fd8a38d02d87be8d/HISTORY.md#public-api-change-13
```
rocksdb_approximate_sizes and rocksdb_approximate_sizes_cf in the C API now requires an error pointer (char** errptr) for receiving any error.
```
if we want to debug sharder on Apple M1 chip, rocksdb has to be upgraded to v6.20.3, and `rocksdb_approximate_sizes` and `rocksdb_approximate_sizes_cf` should be fixed on gorocksdb too. check issue on https://github.com/tecbot/gorocksdb/issues/203

@ssardana08  could you try to send a PR to tecbot/gorocksdb too? we can drop our fork if it is fixed on tecbot/gorocksdb

**Comment by ssardana96** [comment]
@cnlangzi look like there is already a PR opened for the same since March 2021 on the upstream, but not merged
https://github.com/tecbot/gorocksdb/pull/210

**Review by kushthedude — APPROVED** [review]

**Comment by kushthedude** [comment]
Lets get it in since the fork as well as the main library has not been maintained.

**Pull request merged**
